import type { Contradiction, EvidenceSource, Hypothesis, SimulationControls } from "./types";

export const decision = {
  id: "dec-novacell-eu-2027",
  title: "Should Helix launch NovaCell in Germany by Q1 2027?",
  shortTitle: "NovaCell · Germany · Q1 2027",
  recommendation: "CONDITIONAL GO",
  confidence: 78,
  owner: "Strategic Ventures",
  deadline: "04 SEP 2026",
  capitalAtRisk: "$42.0M",
  reversibility: "Medium",
};

export const baselineControls: SimulationControls = {
  marketGrowth: 22.4,
  pricePremium: 14,
  manufacturingYield: 81,
  pilotConversion: 62,
  regulatoryDelay: 4,
};

export const evidence: EvidenceSource[] = [
  {
    id: "E-01",
    source: "Helix Sales Cloud",
    title: "German utility design-partner pipeline",
    body: "Eight German utilities have entered technical discovery. Five signed non-binding design-partner letters representing 184 MWh of potential 2027 demand; three require a sub-€162/kWh installed price.",
    sourceType: "internal",
    stance: "support",
    reliability: 0.86,
    observedAt: "2026-07-11",
    tags: ["demand", "germany", "pipeline", "pricing"],
  },
  {
    id: "E-02",
    source: "Fraunhofer ISE · Test 24-118",
    title: "Independent cell endurance validation",
    body: "NovaCell reference cells retained 82% usable capacity after 410 full-depth cycles at 25°C. Thermal excursion remained inside the submitted safety envelope.",
    sourceType: "technical",
    stance: "support",
    reliability: 0.94,
    observedAt: "2026-06-28",
    tags: ["reliability", "cycle-life", "validation", "safety"],
  },
  {
    id: "E-03",
    source: "Bavaria Pilot Telemetry",
    title: "Field pack degradation exceeds cell model",
    body: "Pack-level telemetry projects the 80% retention threshold at 315 cycles under the utility duty profile. Cooling imbalance explains 61% of observed variance.",
    sourceType: "technical",
    stance: "counter",
    reliability: 0.91,
    observedAt: "2026-07-08",
    tags: ["reliability", "cycle-life", "field", "thermal"],
  },
  {
    id: "E-04",
    source: "Aurora Storage Outlook 2026",
    title: "DACH long-duration storage growth",
    body: "Analyst base case forecasts 23.1% CAGR for four-to-eight-hour storage deployments through 2030, with Germany representing 46% of incremental DACH capacity.",
    sourceType: "market",
    stance: "support",
    reliability: 0.79,
    observedAt: "2026-05-19",
    tags: ["demand", "market-growth", "germany", "storage"],
  },
  {
    id: "E-05",
    source: "Bundesnetzagentur Queue Export",
    title: "Interconnection queue converts slowly",
    body: "Only 9.4% of announced German storage capacity reached an executed interconnection agreement in the trailing 18 months; median queue duration rose to 16.2 months.",
    sourceType: "regulatory",
    stance: "counter",
    reliability: 0.95,
    observedAt: "2026-07-03",
    tags: ["demand", "market-growth", "regulation", "delay"],
  },
  {
    id: "E-06",
    source: "Helix RevOps",
    title: "Stated purchase intent remains high",
    body: "Across 22 discovery calls, 68% of qualified accounts stated they would include NovaCell in a 2027 procurement process if target certification is achieved.",
    sourceType: "internal",
    stance: "support",
    reliability: 0.72,
    observedAt: "2026-06-30",
    tags: ["demand", "conversion", "customer-intent"],
  },
  {
    id: "E-07",
    source: "Paid Pilot Cohort",
    title: "Paid pilot conversion trails interviews",
    body: "Three of seven eligible design partners converted to a paid pilot, a 42.9% conversion rate. Procurement cited warranty clarity and bankability as the principal blockers.",
    sourceType: "customer",
    stance: "counter",
    reliability: 0.9,
    observedAt: "2026-07-13",
    tags: ["demand", "conversion", "paid-pilot", "warranty"],
  },
  {
    id: "E-08",
    source: "NordWerk Supplier Quote NW-88",
    title: "Commercial line yield commitment",
    body: "NordWerk commits to 87% steady-state first-pass yield after the first 10,000 units, subject to a 14-week tooling lead time and annual volume floor.",
    sourceType: "internal",
    stance: "support",
    reliability: 0.74,
    observedAt: "2026-06-14",
    tags: ["manufacturing", "yield", "supply", "unit-economics"],
  },
  {
    id: "E-09",
    source: "Helix Manufacturing Run 6B",
    title: "Current line yield misses commercial case",
    body: "The latest 2,400-unit run achieved 78.2% first-pass yield. Separator alignment and moisture ingress caused 73% of rejected units.",
    sourceType: "internal",
    stance: "counter",
    reliability: 0.96,
    observedAt: "2026-07-15",
    tags: ["manufacturing", "yield", "quality", "unit-economics"],
  },
  {
    id: "E-10",
    source: "EU Innovation Fund Counsel",
    title: "Grant eligibility pathway remains open",
    body: "Counsel assesses a 70–80% probability that German assembly qualifies for the strategic clean-tech manufacturing window, reducing non-recurring engineering cost by €6–9M.",
    sourceType: "regulatory",
    stance: "support",
    reliability: 0.83,
    observedAt: "2026-07-01",
    tags: ["regulation", "subsidy", "capital", "germany"],
  },
  {
    id: "E-11",
    source: "Policy Scenario Memo 17",
    title: "Subsidy timing may slip beyond launch gate",
    body: "The delegated act required for final eligibility may move from November 2026 to March 2027. A four-month delay adds an estimated €3.8M bridge requirement.",
    sourceType: "regulatory",
    stance: "counter",
    reliability: 0.76,
    observedAt: "2026-07-10",
    tags: ["regulation", "subsidy", "delay", "capital"],
  },
  {
    id: "E-12",
    source: "Competitive Teardown · IronCore X4",
    title: "Competitor price advantage is narrowing",
    body: "IronCore X4 is 11% cheaper at system level but occupies 2.3× more space. NovaCell reaches lifecycle cost parity at a 13% price premium for constrained urban sites.",
    sourceType: "market",
    stance: "support",
    reliability: 0.88,
    observedAt: "2026-06-21",
    tags: ["competition", "pricing", "unit-economics", "density"],
  },
  {
    id: "E-13",
    source: "Customer Council · Berlin",
    title: "Warranty term is a hard procurement gate",
    body: "Six of nine procurement leads require a ten-year performance wrap from an investment-grade counterparty. Helix currently has a non-binding seven-year reinsurance indication.",
    sourceType: "customer",
    stance: "counter",
    reliability: 0.89,
    observedAt: "2026-07-06",
    tags: ["customer", "warranty", "bankability", "conversion"],
  },
  {
    id: "E-14",
    source: "Finance Model v41",
    title: "Base case clears investment threshold",
    body: "At 81% yield, 62% pilot conversion, and a 14% price premium, the launch generates $31.6M median risk-adjusted NPV and reaches operating break-even in month 27.",
    sourceType: "internal",
    stance: "support",
    reliability: 0.84,
    observedAt: "2026-07-17",
    tags: ["finance", "npv", "yield", "conversion", "pricing"],
  },
  {
    id: "E-15",
    source: "Red Team Pre-Mortem",
    title: "Correlated downside can exhaust runway",
    body: "A six-month certification delay combined with sub-78% yield and a raw-material spike creates a 19% modeled probability of breaching the board cash floor.",
    sourceType: "internal",
    stance: "counter",
    reliability: 0.82,
    observedAt: "2026-07-18",
    tags: ["risk", "runway", "delay", "yield", "materials"],
  },
  {
    id: "E-16",
    source: "TÜV Rheinland Readiness Review",
    title: "Certification plan has no critical findings",
    body: "The readiness review closed 31 of 34 items. The remaining thermal propagation evidence can be completed inside twelve weeks if the production-intent enclosure freezes by September.",
    sourceType: "technical",
    stance: "support",
    reliability: 0.93,
    observedAt: "2026-07-16",
    tags: ["certification", "safety", "delay", "execution"],
  },
];

export const hypotheses: Hypothesis[] = [
  {
    id: "H-01",
    label: "DEMAND PULL",
    thesis: "German utilities will convert urgency into funded deployments.",
    confidence: 74,
    evidenceIds: ["E-01", "E-04", "E-06"],
    counterIds: ["E-05", "E-07"],
    position: { x: 22, y: 26 },
  },
  {
    id: "H-02",
    label: "UNIT ECONOMICS",
    thesis: "Density advantage sustains a premium at scalable yield.",
    confidence: 81,
    evidenceIds: ["E-08", "E-12", "E-14"],
    counterIds: ["E-09"],
    position: { x: 70, y: 20 },
  },
  {
    id: "H-03",
    label: "FIELD RELIABILITY",
    thesis: "Pack engineering will preserve validated cell performance.",
    confidence: 63,
    evidenceIds: ["E-02", "E-16"],
    counterIds: ["E-03", "E-13"],
    position: { x: 32, y: 72 },
  },
  {
    id: "H-04",
    label: "REGULATORY WINDOW",
    thesis: "Certification and grant gates land before capital is committed.",
    confidence: 76,
    evidenceIds: ["E-10", "E-16"],
    counterIds: ["E-11", "E-15"],
    position: { x: 76, y: 70 },
  },
];

export const contradictions: Contradiction[] = [
  {
    id: "C-01",
    title: "Cell validation ≠ pack reality",
    detail: "Independent cells clear the life gate, while field packs project failure before the warranty threshold.",
    severity: "material",
    evidenceIds: ["E-02", "E-03"],
    delta: "−95 cycles",
  },
  {
    id: "C-02",
    title: "Intent overstates paid conversion",
    detail: "Interview intent and signed pilot behavior diverge materially after procurement scrutiny.",
    severity: "material",
    evidenceIds: ["E-06", "E-07"],
    delta: "−25.1 pts",
  },
  {
    id: "C-03",
    title: "Forecast growth vs. executable queue",
    detail: "Category forecasts imply acceleration that is not yet visible in interconnection execution.",
    severity: "watch",
    evidenceIds: ["E-04", "E-05"],
    delta: "13.7 pts",
  },
  {
    id: "C-04",
    title: "Quoted yield vs. observed yield",
    detail: "Supplier steady-state commitment remains unproven on the current production-intent process.",
    severity: "material",
    evidenceIds: ["E-08", "E-09"],
    delta: "−8.8 pts",
  },
];

export const defaultAudit = [
  { actor: "CONTRARIA", action: "INGEST", detail: "16 sources normalized · 47 claims extracted", createdAt: "2026-07-18T09:42:18Z" },
  { actor: "R. IYER", action: "ASSUMPTION", detail: "Pilot conversion baseline changed 58% → 62%", createdAt: "2026-07-18T10:07:52Z" },
  { actor: "RED TEAM", action: "CHALLENGE", detail: "Correlated certification + yield downside added", createdAt: "2026-07-18T10:18:11Z" },
  { actor: "CONTRARIA", action: "SIMULATION", detail: "10,000 worlds · seed 71422 · model v0.9.3", createdAt: "2026-07-18T10:21:43Z" },
  { actor: "M. WEBER", action: "GATE", detail: "Conditional launch gate approved for review", createdAt: "2026-07-18T11:02:09Z" },
];
